### ISSUE TITLE
Need to define Maine Biotoxin closure areas

### ISSUE THREAD

**Issue by mbrosnahan** [WHOIGit/whoi-hab-hub#1]
Unlike MA and NH, ME does not provide shape files to define their Biotoxin closure areas. Instead closure boundaries are defined by map points/compass headings. They are also redefined frequently. See https://www.maine.gov/dmr/shellfish-sanitation-management/closures/psp.html

**Comment by mbrosnahan** [comment]
Ethan, how are you converting shape files to geojson? 

I looked into editing in Matlab but it's unclear how well I can re-export back out of Matlab to shape or geojson (so possibly a dead end that's not worth pursuing). I've tried coverting above boem files with ogre but am getting errors that I don't understand.

http://ogre.adc4gis.com

Once converted I'm hoping it might be straightforward to make shapes from coast and jurisdiction lines using geojson.io or some other similar tool. Still waiting for some direction from GIS-types at USGS - hopefully they can point us to the easiest/most effective way to accomplish creation of new shapes from these lines and boundaries that Claire is compiling.

**Comment by ethanandrews** [comment]
Hi Mike

I used that same ogre online tool that you linked to:

https://ogre.adc4gis.com/

I did have to specify the Target SRS as “EPSG:4326”, otherwise the coordinates didn’t match up to real lat/long.

I just followed the instructions here:

https://www.statsilk.com/maps/convert-esri-shapefile-map-geojson-format

I’m sure there’s an export function for ArcGIS online, but you may have to upgrade from the free account that Claire has?

**Comment by mbrosnahan** [comment]
Thanks for above, Ethan. I just got this from Zafere Defne over at USGS. Sounds like he's willing to create ME geojson zones for us!

Begin forwarded message:
