### ISSUE TITLE
Icons for closures

### ISSUE THREAD

**Issue by kalimhorn** [WHOIGit/whoi-hab-hub#7]
Not sure the best ways to share these, but here an image of some of the icons I found/created. Ideas? Favorites?

<img width="753" alt="Screen Shot 2021-01-07 at 11 49 00 AM" src="https://user-images.githubusercontent.com/73716251/103919789-76248a00-50de-11eb-86d7-cfb900228c8f.png">

**Comment by mbrosnahan** [comment]
Hi all,

I took a quick look at gettyimages and searched 'warning sign', 'no fishing sign', and 'no shellfishing sign'.

Top hit from 'warning sign' was a yellow/orang triangle with an exlamation point inside. Nice enough and sort of fits current closure area color. See others at:
https://www.gettyimages.com/illustrations/warning-sign?family=creative&phrase=warning%20sign&sort=mostpopular	

Hits for 'no fishing sign' weren't any good because they focus on finfish. Check out:
https://www.gettyimages.com/photos/no-fishing-sign?family=creative&license=rf&phrase=no%20fishing%20sign&sort=mostpopular#license

Search for 'no shellfishing sign' was pretty lackluster but warning/! result was #6.
https://www.gettyimages.com/photos/no-shellfishing-sign?family=creative&license=rf&phrase=no%20shellfishing%20sign&sort=mostpopular#license

I still like the mussels and will be interested in using Kali's #6 for Mussel toxicity icons. Idea to make 6 variants shaded by PSP level is great. In near term, we'd only use the 'PSP palette'. Later we would likely extend to a second 'ASP palette' set.
